#!/bin/sh

set -e
exec 3>&1
exec 1>&2

# for jq
PATH=/usr/local/bin:$PATH

inputs=$(mktemp /tmp/resource-in.XXXXXX)

cat > $inputs <&0

app_id=$(jq -r '.source.app_id' < $inputs)

api_key=$(jq -r '.source.api_key' < $inputs)

json_file=$(jq -r '.params.json_file // ""' < $inputs)

user=$(jq -r '(.params.user // empty)' < $inputs)


if [[ -n "${json_file}" && -f "${json_file}" ]]
then
  check=$(jq '.revision?' $json_file)
  if [[ $check == null ]]
  then
    echo "revision is missing from the json_file. cannot continue"
    exit 1
  fi

  revision=$(jq -r '.revision' $json_file)
  changelog=$(jq -r '(.changelog // empty)' $json_file)
  description=$(jq -r '(.description // empty)' $json_file)
fi

body=$(jq -c -n \
	--arg revision "${revision}" \
	--arg changelog "${changelog}" \
	--arg description "${description}" \
	--arg user "${user}" \
	'{
		deployment: {
			revision: $revision,
			changelog: $changelog,
			description: $description,
			user: $user
		}
	}'
)

RESPONSE=$(curl -X POST "https://api.newrelic.com/v2/applications/${app_id}/deployments.json" \
     -H "X-Api-Key:${api_key}" -i \
     -H "Content-Type: application/json" \
     -d ${body})



STATUS=$(echo $RESPONSE | grep HTTP |  awk '{print $2}')

if [ "$STATUS" -ne "200" ] && [ "$STATUS" -ne "201" ]; then
  echo $RESPONSE
  exit 1;
fi


jq -n \
    --arg ts $(date +%s) \
    --arg revision "${revision}" \
    --arg changelog "${changelog}" \
    --arg description "${description}" \
    --arg user "${user}" \
    '{
        version: {
            timestamp: $ts
        },
        metadata: [
            {name: "revision", value: $revision},
            {name: "changelog", value: $changelog},
            {name: "description", value: $description},
            {name: "user", value: $user}
        ]
    }' >&3