#!/bin/sh

set -e
exec 3>&1
exec 1>&2

# for jq
PATH=/usr/local/bin:$PATH

inputs=$(mktemp /tmp/resource-in.XXXXXX)

cat > $inputs <&0

app_id=$(jq -r '.source.app_id' < $inputs)

api_key=$(jq -r '.source.api_key' < $inputs)

revision=$(jq -r '(.params.revision // null)' < $inputs)

changelog=$(jq -r '(.params.changelog // null)' < $inputs)

description=$(jq -r '(.params.description // null)' < $inputs)

user=$(jq -r '(.params.user // null' < $inputs)

curl -X POST 'https://api.newrelic.com/v2/applications/${app_id}/deployments.json' \
     -H 'X-Api-Key:${api_key}' -i \
     -H 'Content-Type: application/json' \
     -d \
'{
  "deployment": {
    "revision": "${revision}",
    "changelog": "${changelog}",
    "description": "${description}",
    "user": "${user}"
  }
}'